source 'https://rubygems.org'

gem 'rails', '~> 4.1.1'
gem 'pg', '~> 0.16.0'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails', '~> 3.0.4'
gem 'turbolinks', '~> 1.3.0'
gem 'haml', '~> 4.0.2'
gem 'haml-rails'
gem 'bootstrap-sass', '~> 3.0.3.0'
gem 'responders', '~> 1.0.0'
gem 'exception_notification', '~> 4.0.1'
gem 'simple_form', '~> 3.0.1'
gem 'show_for', '~> 0.3.0.rc'
gem 'rails_config', '~> 0.3.3'
gem 'compass-rails'
gem 'compass'
gem 'devise', '~> 3.2.4'
gem 'devise-i18n', '~> 0.9.0'
gem 'will_paginate', '~> 3.0.4'
gem 'will_paginate-bootstrap', '~> 0.2.3'
gem 'will-paginate-i18n', '~> 0.1.13'
gem 'paperclip', '~> 3.5.1'
gem 'rack-timeout', '~> 0.0.4'
gem 'annotate', '>=2.5.0'
gem 'recipient_interceptor', '~> 0.1.2'
gem 'rails-i18n', '~> 4.0.1'
gem 'ransack', '~> 1.2.3'
gem 'capistrano', '~> 2.15.5'
gem 'capistrano-ext', '~> 1.2.1'
gem 'unicorn', '~> 4.8.2'
gem 'aws-sdk', '~> 1.29.0'

# gem 'rails-observers'

gem 'breadcrumbs_on_rails', '~> 2.3.0'

group :development, :test do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'letter_opener'
  gem 'bullet'
end

gem 'redactor-rails', '~> 0.4.5'
gem 'carrierwave'
gem 'mini_magick'

gem 'bootswatch-rails'
gem 'friendly_id'